// content/imageScanner.js (v0.4.2)
(function(){
  function getCfg(){ return new Promise(resolve=>{ chrome.storage.local.get({ asg_scanImages:true }, resolve); }); }
  function heuristics(img){ const keys=[]; let level='ok'; const w=img.naturalWidth, h=img.naturalHeight; if(!w||!h) return {level:'warn', reasonKeys:['NO_SIZE'], suggestionKey:'IMG_SUGGESTION'}; const ratio=Math.max(w,h)/Math.min(w,h); if(ratio>3){ keys.push('EXTREME_RATIO'); level='warn'; } if(w*h<200*200){ keys.push('LOW_RES'); level='warn'; } const src=(img.currentSrc||img.src||'').trim(); if(src && !/^https:/.test(src) && !src.startsWith('data:')) { keys.push('NON_HTTPS'); level='warn'; } return {level, reasonKeys:keys, suggestionKey:'IMG_SUGGESTION'}; }
  function show(p){ const ensure=()=>new Promise(res=>{ if(window.__ASG_showWarning) return res(); const s=document.createElement('script'); s.src=chrome.runtime.getURL('content/overlay.js'); s.onload=res; document.documentElement.appendChild(s); }); ensure().then(()=> window.__ASG_showWarning && window.__ASG_showWarning(p)); }
  function scanOne(img){ try{ const r=heuristics(img); if(r.level!=='ok') show(r); }catch{} }
  function scanNodeForImages(root){ try{ if(root && root.tagName==='IMG'){ if(root.complete) scanOne(root); else root.addEventListener('load',()=>scanOne(root),{once:true}); } if(root && typeof root.querySelectorAll==='function'){ Array.from(root.querySelectorAll('img')).forEach(im=>{ if(im.complete) scanOne(im); else im.addEventListener('load',()=>scanOne(im),{once:true}); }); } }catch{} }
  function init(){ getCfg().then(({asg_scanImages})=>{ if(!asg_scanImages) return; Array.from(document.images||[]).forEach(im=>{ if(im.complete) scanOne(im); else im.addEventListener('load',()=>scanOne(im),{once:true}); }); const mo=new MutationObserver(muts=>{ for(const m of muts){ if(m.addedNodes && m.addedNodes.length){ Array.from(m.addedNodes).forEach(n=>scanNodeForImages(n)); } } }); mo.observe(document.documentElement,{childList:true,subtree:true}); }); }
  init();
})();
